# Generated by Django 2.0.3 on 2018-04-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_age',
            field=models.PositiveIntegerField(blank=True, default=20),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_phone_no',
            field=models.CharField(blank=True, default='9889059224', max_length=20),
        ),
    ]
