# Generated by Django 2.0.3 on 2018-04-09 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0003_auto_20180409_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_phone_no', models.CharField(blank=True, max_length=20)),
                ('seller_age', models.PositiveIntegerField(blank=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
