# Generated by Django 2.0.3 on 2018-04-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_sellerprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofileinfo',
            name='seller',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='type_of_user',
            field=models.CharField(default='seller or customer', max_length=20),
        ),
        migrations.DeleteModel(
            name='SellerProfileInfo',
        ),
    ]
