# Generated by Django 2.0.3 on 2018-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20180409_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='type_of_user',
            field=models.CharField(blank=True, default='seller or customer', max_length=20),
        ),
    ]
