# Generated by Django 2.0.4 on 2018-04-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20180410_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first_app.UserProfileInfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first_app.Product')),
            ],
        ),
    ]
